name: SQLMap SQL Injection Scan

on:
  workflow_dispatch:

jobs:
  sqlmap-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Install SQLMap
        run: |
          sudo apt-get update
          sudo apt-get install -y sqlmap

      - name: Create results directory
        run: mkdir -p ./sqlmap-results

      - name: Run SQLMap Scan (Safe Mode)
        run: |
          # -----------------------------------------------------------------
          # !!! 警告 !!!
          # スキャンが 403 Forbidden で失敗する場合、
          # サーバー側のWAF設定で「GitHub ActionsのIPアドレス」を
          # 許可リストに追加する必要があります。
          #
          # !!! 必須 !!!
          # "https://your-test-site.com/search.php?query=test" の部分を
          # あなたの「テスト環境」の「パラメータ付きURL」に変更してください。
          # -----------------------------------------------------------------
          sqlmap -u "https://reitouko.site/blog/wp-login.php?redirect_to=https%3A%2F%2Freitouko.site%2Fblog%2Fwp-admin%2F&reauth=1" \
            --privileges \
            --output-dir=./sqlmap-results \
            --answers="quit=N"
            
          # --level=1, --risk=1 : 最も安全で基本的なテストのみ実行
          # (注: あなたのコードは level=3, risk=3 になっていましたが、
          #      コメントと食い違っており、非常に危険な設定です)

      - name: Upload SQLMap Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sqlmap-results
          path: ./sqlmap-results/
