name: SQLMap SQL Injection Scan

on:
  # Actionsタブから手動でのみ実行する
  # (危険なため、スケジュール実行は強く非推奨)
  workflow_dispatch:

jobs:
  sqlmap-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Install SQLMap
        run: |
          sudo apt-get update
          sudo apt-get install -y sqlmap

      - name: Create results directory
        # レポート保存用のディレクトリを作成
        run: mkdir -p ./sqlmap-results

      - name: Run SQLMap Scan (Safe Mode)
        run: |
          # !!! 必須: あなたの「テスト環境」の「パラメータ付きURL」に変更してください
          sqlmap -u "https://reitouko.site/blog/wp-login.php?redirect_to=https%3A%2F%2Freitouko.site%2Fblog%2Fwp-admin%2F&reauth=1" \
            --batch \
            --level=3 \
            --risk=3 \
            --output-dir=./sqlmap-results \
            --answers="quit=N"
            
          # --batch : CIで実行するために必須（すべての質問にデフォルトで回答）
          # --level=1, --risk=1 : 最も安全で基本的なテストのみ実行
          # --output-dir : 結果の出力先
          # --answers="quit=N" : 途中で「終了しますか？」と聞かれた場合に「N (いいえ)」と答える

      - name: Upload SQLMap Results
        # スキャンが成功しても失敗しても、ログをアップロードする
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sqlmap-results
          path: ./sqlmap-results/
