name: WPScan Security Test

on:
  # 'Actions' タブから手動で実行できるようにします
  workflow_dispatch:

jobs:
  wpscan-audit:
    runs-on: ubuntu-latest

    steps:
      # 1. リポジトリをチェックアウトします
      # (チェックアウトしないと、ワークスペースが作成されないため)
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. WPScan が依存する Ruby の環境をセットアップします
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1' # WPScan と互換性のある Ruby バージョン

      # 3. WPScan の実行に必要なライブラリをインストールします
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libxml2-dev libxslt1-dev libffi-dev

      # 4. WPScan 本体を gem からインストールします
      - name: Install WPScan
        run: gem install wpscan

      # 5. SecLists からパスワードリストをダウンロードします (NEW)
      - name: Download Password List (Lizard-Squad.txt)
        run: |
          # curl を使って指定されたURLのrawコンテンツをダウンロードし、Lizard-Squad.txtとして保存します
          curl -L -o Lizard-Squad.txt https://raw.githubusercontent.com/danielmiessler/SecLists/master/Passwords/Leaked-Databases/Lizard-Squad.txt
          echo "Password list downloaded."
          ls -lh Lizard-Squad.txt # ダウンロードされたことを確認

      # 6. WPScan を実行します
      - name: Run WPScan
        run: |
          # 警告: このコマンドは http://localhost をターゲットにしているため、
          # GitHub Actions ランナー自身を指し、接続エラーで失敗する可能性が高いです。
          wpscan --url https://reitouko.site/ --passwords Lizard-Squad.txt --usernames yuki571 --no-update
