name: Generate 100 numeric strings (Luhn check)

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    outputs:
      generated_ids: ${{ steps.gen.outputs.ids }}
      luhn_passed: ${{ steps.gen.outputs.luhn_passed }}
    steps:
      - name: Generate 100 numeric strings
        id: gen
        shell: bash
        run: |
          set -euo pipefail

          PREFIX="471618"
          COUNT=100
          IDS=()
          LUNHS=()

          # Luhn チェック関数
          luhn_valid() {
            local n="$1"
            local sum=0
            local len=${#n}
            local i
            for (( i=0; i<len; i++ )); do
              local d=${n:len-1-i:1}
              local v=$d
              if (( i % 2 == 1 )); then
                v=$((v*2))
                (( v > 9 )) && v=$((v-9))
              fi
              ((sum+=v))
            done
            (( sum % 10 == 0 ))
          }

          for ((j=0;j<COUNT;j++)); do
            RAND=$(head /dev/urandom | tr -dc '0-9' | head -c 10)
            NUM="${PREFIX}${RAND}"
            IDS+=("$NUM")
            if luhn_valid "$NUM"; then
              echo "Luhn check PASSED — $NUM"
              LUNHS+=("true")
            else
              LUNHS+=("false")
            fi
          done

          # 配列を文字列にして出力
          echo "ids=${IDS[*]}" >> "$GITHUB_OUTPUT"
          echo "luhn_passed=${LUNHS[*]}" >> "$GITHUB_OUTPUT"

      - name: Write IDs to file
        run: |
          echo "${{ steps.gen.outputs.generated_ids }}" | tr ' ' '\n' > generated_numeric.txt
          cat generated_numeric.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: generated-numeric
          path: generated_numeric.txt
